### ISSUE TITLE
MyMatch internationalization

### ISSUE THREAD

**Issue by mothprog** [trashmai/MyMatch#1]
Now we are preparing to build an instance of MyMatch service. The target people are not familiar to English (and also Chinese), we are trying to translate the interface into Japanese. We feel some difficulties for translation because many sentences such as error messages are embedded in the source code. So we are pleased if you try to move messages to a separate include file as constants, like:

before:
/include/queryNames.php
extract_results($query_url_1_err, "Type 1-e: Full match with minor err", $reset=false, $against);

after:
/include/error_messages.inc
define("ERR_TYPE1E", "Type 1-e: Full match with minor err");
/include/queryNames.php
extract_results($query_url_1_err, ERR_TYPE1E, $reset=false, $against);

We can check changes of message even if they are changed in future versions. So such improvements are useful for our translation. Also, these change is useful to construct instances in other languages. Thank you very much.

**Comment by trashmai** [comment]
Thanks for your feedback!
Messages are extracted from original code and are put into conf/lang/error_codes.php (default).
You can either change the file contents directly or make a copy to error_codes.{lang}.php. The latter would need you to add/edit a line inside form section in index.html, for example:
`<input type='hidden' name='lang' value='zh'/>`
to show messages defined in conf/lang/error_codes.zh.php.
If the conf/lang/error_codes.{lang}.php doesn't exist, it will fall back to default (error_codes.php)

**Comment by mothprog** [comment]
Thank you. We will prepare Japanese translation, which file name might be error_codes.ja.php .
