### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by mothprog** [trashmai/MyMatch#2]
Hello. I would like to ask about the security matters of MyMatch.
As far as I checked, the program seems not to sanitize HTML tags, so I am afraid that there are security holes such as XSS. At least, when I input "Papilio <!--", the remaining table has been commented out. I think the system had better to sanitize any inputted strings, that is, replace meta characters in inputs to 
character entity references.

**Comment by trashmai** [comment]
Thanks for the important reporting! User-input names are now encoded before outputting as html table. This should do the trick?

**Comment by mothprog** [comment]
Thank you very much for your prompt commit! Yes it meets my request.
Many people are so nervous about security issues, so I will submit reports when we know another issues.
